code for adding tables to database
WulffMorgan/Projektuppgift-Ljudio pull request #15
Opened 2021-02-11 09:01 UTC by Skander-Damoussi

2021-02-11 09:29 UTC, WulffMorgan requested changes
Skapa tabeller utefter vår diskussion

2021-02-11 23:08 UTC, NicklasSoderberg approved these changes

2021-02-11 23:15 UTC, NicklasSoderberg commented
Antar att pushen efter din review är lösningen? men kan inte approva då du är admin och lagt "Changes requested".

2021-02-12 08:06 UTC, WulffMorgan approved these changes

2021-02-12 08:06 UTC, merged